### ISSUE TITLE
Nighelles' complaints

### ISSUE THREAD

**Issue by nighelles** [remulasce/metroapp#126]
1) There's no reason to have to push the right arrow button after selecting your stop in the auto prediction drop down.

**Comment by nighelles** [comment]
2) If I was using this app to keep track of several stops I have to use during the week, then the nearest arrival next display for my stops is kinda confusing. Imagine like 4 stops. At least put like, a heavier bar between groups of busses in that display.

**Comment by nighelles** [comment]
Addendum to last point.

I guess it depends on if you envision people using the app to look up a bus they need soon, then finding their bus, setting a notification, and then deleting it after. Or if you're thinking this is like, an app you'd use for the same bus every day.

**Comment by remulasce** [comment]
1) added to Release Milestone, #127
2) Yeah, you're only supposed to add on the stops you need for your current trip, and add/delete stops as you approach or need them if it's too busy.

Addendum:
2) Better arrival display ordering is slated for Dev Cycle 2 for connecting trips (Milestones tab, (more) under dev_2). I'm moving this issue to that milestone.

**Comment by remulasce** [comment]
1) Fixed.

**Comment by remulasce** [comment]
2) Also fixed now.
