### ISSUE TITLE
Use a geotable instead of SQL for nearest-stop searching

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#157]
We're currently using a very naive get-everything-then-rank algorithm to calculate autocomplete entries.
This gets pretty slow.

We should use a dedicated spatial database instead.
The database should have internal methods to return closest things first, and should be much faster.

**Comment by nighelles** [comment]
Well, thats true if we expect users to be searching for busses closer to them. I don't know if this use case encompasses people trying to ride all the busses in one day.

**Comment by remulasce** [comment]
Who would be able to do that? There's like a hundred of them.

**Comment by nighelles** [comment]
Heroes.

**Comment by nighelles** [comment]
Ok, so indexing on lat and long with a filter step before doing geolocation distance math seems fast enough in my implementation. There aren't that many stops, so I'm closing this.
