### ISSUE TITLE
Platform-abstract Analytics code

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#169]
Need compatibility layer so we don't have to import Google Analytics directly in Java_Core

**Comment by nighelles** [comment]
Yes, that would be ideal.

**Comment by remulasce** [comment]
Functions:
- Send event
  - Category: "About Page"
  - Action: "Pane Opened"
  - Optional label "About Page Button"
- Set Screen Name

**Comment by remulasce** [comment]
Screen name is in.

**Comment by remulasce** [comment]
Event reporting implemented
Re-instated in MainActivity

Analytics realtime verifies both screen names and events are actually getting sent.

**Comment by remulasce** [comment]
And analytics is all platform-independent!
