### ISSUE TITLE
Moderately close stations all show distanceto as "0.0"

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#170]
It's probably a combination of poor rounding and not changing to "x feet" when you get really close.

**Comment by nighelles** [comment]
How did you do that math? lat and long aren't rectangular coordinates.

**Comment by remulasce** [comment]
Android builtin library.

**Comment by remulasce** [comment]
Done on dev_4 daa933

**Comment by remulasce** [comment]
We go down to yards on <100yd, cut off the decimal after 10 miles, and display "really far" from 100 miles away.
