### ISSUE TITLE
Static data port support

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#176]
Java_core doesn't have any of the static data provided by Metro.
Currently java_core has enough to do 'predictions', but not any of the convenience methods of actually making servicerequests.
Parsing that stuff is really annoying, and should be similar enough for most of it to be reused between platforms.

So, we should figure out a way to reuse the SQL tables, etc in java_core.

**Comment by remulasce** [comment]
Looks like some of the static translator interfaces made it into java_core
Just not  the actual difficult parts.

**Comment by remulasce** [comment]
Nighelles is something-or-other-ing this.

**Comment by nighelles** [comment]
I have a container class that abstacts the sql database on IOS. If you want to do this in java somewhere, we can see if the sqlite3 java code works crossplatform, otherwise it seems fine to leave it as a difference cross platform, as I don't see the sql code changing much.

**Comment by remulasce** [comment]
This is more an enhancement than necessary now that Nighelles already reimplemented everything.

Closing.
