### ISSUE TITLE
Random "metro app has stopped working"

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#189]
Don't know the cause.
Happens when app is both in foreground and background
... so probably something is also not getting shut down properly.

**Comment by nighelles** [comment]
Hmm

**Comment by remulasce** [comment]
Clarification: Only noticed on dev_2 branch after implementing synchronized stop-proximity updating.

**Comment by remulasce** [comment]
I integrated an exception-reporter library which prompts the user to email me with a stack trace and other info.

So next time it happens I'll have any sort of clue of what actually happened.

**Comment by remulasce** [comment]
Looks like it was a problem in NotifyService. Null pointer check / handling have resolved it. The Report A Crash thing is great, though.
