### ISSUE TITLE
Add 'Rate app' bogus reminder.

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#202]
Getting people to review the app is good.
Especially if we get to not actually forward them if they have bad reviews, like how the evil companies do it.

So if there's a library that does this for us, let's add it.

**Comment by nighelles** [comment]
Lol, you mean like present a rate the app dialog, and only link them to the actual store if they put 5 stars?

**Comment by remulasce** [comment]
Yup. That's how all the evil games do it.

I'm going to put it off for now, since we only have like 10 users, and I'd feel bad showing it to that one guy who donated $5.
