### ISSUE TITLE
Test setting up a new workspace from VC

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#203]
We should do this occasionally anyway, but especially after we rejiggered the project structure we should make sure it's still reasonable enough to pull frog GH and start working quickly.

**Comment by remulasce** [comment]
On my desktop, everything was setup immediately in a newly pulled git folder.
Maybe check how long it takes to setup Android Studio?

Documentation is still sorely lacking though, as Nighelles can probably attest.

**Comment by remulasce** [comment]
And, I don't know what setup has to be done to make the iOS part work.

**Comment by nighelles** [comment]
I don't know if you can get it to work immediately on IOS by pulling from git. I'd imagine so, but I still can't get the android version to compile in AS

**Comment by remulasce** [comment]
Do you have more specific errors than that?

**Comment by nighelles** [comment]
Yes, but I contacted you outside github.

**Comment by nighelles** [comment]
Error:Execution failed for task ':app:processDebugManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: java.io.FileNotFoundException: /REDACTED/app/build/intermediates/exploded-aar/com.android.support/support-v4/21.0.0/AndroidManifest.xml (No such file or directory)

**Comment by nighelles** [comment]
Sort of fixed?

**Comment by nighelles** [comment]
Ok fixed, unrelated: DAMN the android emulator takes a long time to start.

**Comment by nighelles** [comment]
It might be faster to wait for Remulasce to mail me a dev device than to wait for the emulator to start running.
