### ISSUE TITLE
Disclaimer probably required

### ISSUE THREAD

**Issue by nighelles** [remulasce/metroapp#209]
We should probably add a window when the app first launches that displays a disclaimer to the effect that we're getting our data from nextbus and it is not guaranteed to be accurate.

**Comment by remulasce** [comment]
Ugh. Popup windows are so lame on startup.

**Comment by nighelles** [comment]
You'd only have to do it once the first time they open the app.

**Comment by remulasce** [comment]
Yeah. That's what's lame. That's literally their first impression of the app. We should at least wait until the user knows the app is useful at all before we start bothering him/her.

**Comment by nighelles** [comment]
I mean, it's a liability thing. If you want to eat the liability, I dunno.

**Comment by nighelles** [comment]
Maybe put the warning at the bottom of the app description.

**Comment by remulasce** [comment]
It's in the app description and in the Legal / Info button.
What kind of liability do you expect we're assuming?
