### ISSUE TITLE
Get Paid

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#212]
We got a $5 donation.

PayPal immediately took 45c for itself.
Leaving us with $4.55.

We need to get that $4.55 out of PayPal.
Options are to either:
- Link a bank account and direct transfer
- Pay $1.50 for them to mail a check.

I kind of want to hang a check up in a picture frame or something, so mailing a check would be convenient.
But, it also takes us down to only 60% of the donated value.

Also I don't want PayPal to have my bank info.

**Comment by nighelles** [comment]
Oh just assign me to whatever, is that it?

**Comment by nighelles** [comment]
Mail a check, that is so much cooler.

**Comment by remulasce** [comment]
Check for $3.05 requested. ETA 1-2 weeks.

**Comment by nighelles** [comment]
Can no longer reproduce.

**Comment by remulasce** [comment]
Reopening. Payment not found.

**Comment by nighelles** [comment]
Vendor has assured us it is dealt with, reclosing.
