### ISSUE TITLE
IOS: requestStatusTrip is all

### ISSUE THREAD

**Issue by nighelles** [remulasce/metroapp#213]
I get a requestStatusTrip, present a loading beachball, and then that's it. I never get a multiArrivalTrip from the SRDA

**Comment by remulasce** [comment]
Suggest you try debugging.

**Comment by nighelles** [comment]
Ugh, TCP snooping claims that we're getting no response from the server to the request sent from the ios app.

-Nighelles

**Comment by nighelles** [comment]
Ok, what the hell? The server responded to a different request from the app like 30 s later. Is there a difference between one request and the next?

**Comment by nighelles** [comment]
Status trip thing didn't disappear when we got an update, and also we only have like one XML response from like 5 min of running the app on the snooper. What's up with that, org.internet.whatever

**Comment by nighelles** [comment]
So it looks like the GET requests are getting out fine, but there's no response from the network. Which is odd, cause doing the same GET request that wireshark says the ios version is sending in chrome gives the intended XML. So WTF? Did nextbus intentionally cripple this particular thing? Lol.

**Comment by nighelles** [comment]
Now it looks like old working code won't return good network on the ios simulator either, though it's still working on my phone. Did nextbus actually change something?

**Comment by nighelles** [comment]
Lol, ok, now it's working. It was apparently a problem with the network adapter in the IOS SIMULATOR.

Issue closed.
