### ISSUE TITLE
Confirmation Dialog for Notification Service lets you hit ok even if there's no vehicles.

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#217]
It's possible to have a Trip with 0 arrivals once the last bus has arrived.

If you tap on it, the notify service will happily let you hit 'ok' even though there's no vehicles available to select.
Preliminary test shows that notify service subsequently totally fails.

It used to be that you didn't have to specify a vehicle. But that hasn't been a use case for a while.
At minimum the dialog shouldn't let you hit 'ok' if there's no vehicles, since we already know nothing's coming.

**Comment by nighelles** [comment]
Fixed, probably. But I can't test it easily without waiting until the last bus of the day.

**Comment by nighelles** [comment]
I also tried asking for a reminder after the bus arrived, which was allowed but instantly reminded me. In addition, I testing opening the reminder dialog, waiting till the bus arrived, and then hitting ok, which was fine also. Nothing happened.

**Comment by nighelles** [comment]
Tempted to just change the radio button text when there's no buses to just "crash app", reenable the Ok button, and label this "feature not bug"

**Comment by nighelles** [comment]
Tested, fixed.
