### ISSUE TITLE
Update donation pitch / process

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#219]
We got a donation!

Let's see what we can do to get more, and how to reward donations.

From 2 months of availability, we have some metrics about monetization, hillariously.

Currently our only monetization is a donate button on the left-menu pane.
You can only bring up the pane by pressing the 'sandwich' in the top-left app icon, or by swiping left from the main screen.

There's a static 2-sentence pitch just above the button. It has a characterization line and a call to action.
I think those are businessie words.

The button reads 'Donate' and is unadorned.

Analytics shows the pane gets about 10 views per day, representing about 5% of reported screen views.
The button has been pressed 26 times in total, not including my presses.
I have received one donation, for $5.

I have approx 10 daily users, which is down from 20 in post-release peak but slowly climbing.
I have about 80 current installs, and 100+ total installations.

**Comment by remulasce** [comment]
The 5% screen-view count is actually pretty good, I think, since there's no other reason to open the pane.

But overall discoverability is still low, I think.

The pitch is an ok pitch, for 2 sentences.
But there's a lot left on the table. Perhaps more pitches in more places?

The button itself kind of sucks.
Presentation of the pitch is good, and the button is in a prominent position given about pane, but the button is absolutely plain and unadorned.

It literally just says "Donate". In a regular-style button. Absolutely nothing distinguishing it, other than the placement.

Once you hit the button, things fall off. You have to select a browser app to open the PayPal donation website.

The paypal screen gets the job done, but there's absolutely no pitch there. The default donation value is $0.00. The only things linking it to me is it shows the email- lametrodeveloper@gmail- up top. And with a button press on the 'select amount' line, you get "La Metro Companion | Fintan O'Grady". Real nice.

**Comment by remulasce** [comment]
And finally, once you donate, I get an email and take back over, writing you a nice emailed/reddit comment reply almost immediately. But there's no in-app recognition of donations, which may affect future premium feature stuff.

**Comment by nighelles** [comment]
Ok, so we're screwed. People on reddit never push buttons.

**Comment by remulasce** [comment]
#buttongate 2015

**Comment by remulasce** [comment]
#yolo

**Comment by remulasce** [comment]
So I've thought of a couple improvements.

- Bring up the about pane occasionally
 - this could be a usability problem, so have to think carefully about this.
- Pitch Improvements
 - It's a good pitch, but we shouldn't be limited to one pitch.
 - How about several pitches, which rotate out each load?
- Pitch Presentation
 - Popup "donate pls" screens are lame, but probably effective.
 - We can probably figure out a way to put the pitch in more places without being too annoying.
- Button decorations
 - Button should at minimum be a different color.
 - Custom graphics would be nice as well.
 - Different font would be nice.
- Donations Counter
 - A "# of donations" ticker. Increments every donation.
  - I don't want  to deal with automating this, so I'd have to manually update the app every donation.
   - This is ok with my level of donations. And make for hillarious update texts.
- PayPal improvements
 - Need to investigate improving that paypal screen
 - Actually, the app is still running in the background. I can put up Toasts while the user is on that page.

**Comment by remulasce** [comment]
Donate button is gold, now with more bigger!

**Comment by nighelles** [comment]
Maybe add a "please checkout the about page" memo to the bottom of the reminder that your bus is about to arrive if you haven't yet donated.

**Comment by remulasce** [comment]
Hmm. The memo is a good place for a something-or-other. I'm not sure how to work in a call to action from there.

Maybe when you tap the notification to go to the app, it brings you to the about page instead of the main page, like it does now?

**Comment by remulasce** [comment]
#### Pitch Discoverability

We could add a "look at the about screen <----" text below the existing tutorial text.
If we want to be fancy, we could even get rid of the current tutorial text once the user figures out how to use everything.

**Comment by nighelles** [comment]
Yeah, maybe the tutorial is a good place for it. I don't think going to the about page by default is a nice thing to do.

**Comment by remulasce** [comment]
"X users have donated" text added just below the donate button.

**Comment by nighelles** [comment]
That's good. Maybe like, a countdown timer, with like, nobody knows what happens if nobody donates within 60s.

**Comment by nighelles** [comment]
Maybe artificially inflate the number too, so that it looks like people are donating all the time.

**Comment by nighelles** [comment]
Just say "appox X people" have donated

**Comment by remulasce** [comment]
Hmm. Most of the users currently using it are early adopters. I think they'd be a little suspicious of inflated donation counts. Especially since you can see in the app store that there's only 100 installs.

At minimum, counter inflation should start with 1, and then slowly work its way up.

**Comment by remulasce** [comment]
Added a Toast-style pitch once they hit the "Donate" button. 3 onscreen messages queue up and get displayed while they are at the Paypal donation site.

**Comment by nighelles** [comment]
Maybe just slowly inflate it. Like 2.45 people have donated. Now 2.46 people have donated.

**Comment by nighelles** [comment]
Lol.

**Comment by remulasce** [comment]
2.5, +- 3.1

**Comment by remulasce** [comment]
[-1, 4)

**Comment by nighelles** [comment]
Sum_1^n 1

**Comment by remulasce** [comment]
Good enough for round 1 of pitch improvements.
So we're not going to touch the actual pitch / rotate out pitches.

**Comment by remulasce** [comment]
Added a call to action under my email, to give avenue for people who won't donate.
