### ISSUE TITLE
IOS UI differences

### ISSUE THREAD

**Issue by nighelles** [remulasce/metroapp#221]
How do we want to handle differing design options on the ios version. The example that comes to mind is the notification popup. I have it set right now so that each option is a button, (only 2 min notices are available so far) and theres a cancel button. No radio buttons available on ios unless you want me to design them myself.

**Comment by remulasce** [comment]
Sounds good.

Allowing differing design is like half the reason we're using j2objc and not some weird middleman library.
As long as all the business logic is in java_core, differing UI is a feature, not a bug.

**Comment by nighelles** [comment]
Wait, there's a category for that?

Really, the issue with that UI decision is that I'm not sure how to set the time you want. Maybe like a selector thing at the top, but then it would only be a fixed number of options.

**Comment by remulasce** [comment]
Text field?

**Comment by nighelles** [comment]
Ugh, that really doesn't sounds nice.

**Comment by remulasce** [comment]
I think most of the time you don't need to change the default value.
Android version uses text field, though Android provides built in filtering
to force numbers only.

**Comment by nighelles** [comment]
I mean, I can do that too, but it like, pops the keyboard up, and you have to exit out after unless I squish the popup for the dialog to the top of the screen.

**Comment by remulasce** [comment]
Oh yeah. Android does that for you to.

**Comment by nighelles** [comment]
Yeah, but then there's like an additional step.

**Comment by nighelles** [comment]
Also, the devs on this project are super responsive.
