### ISSUE TITLE
Android project won't load from git.

### ISSUE THREAD

**Issue by nighelles** [remulasce/metroapp#222]
I've been trying to run the android version of the app, and android studio doesn't seem to want to import the project from the git file. Are the non-code things included in the git repo?

**Comment by remulasce** [comment]
Could not reproduce in new git directory on desktop.

git clone https://github.com/remulasce/metroapp
Android Studio Open->lametroapp folder (root)

**Comment by remulasce** [comment]
"Open" command was from an existing project. Dialog shown read "Open file or existing project".

the lametroapp folder should have an icon in that dialog that shows it's an AS project.

**Comment by remulasce** [comment]
Is this resolved, @nighelles ?

**Comment by nighelles** [comment]
Not yet.
