### ISSUE TITLE
NexTrip scraper doesn't check for duplicate stops properly.

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#229]
Line 60 checks stopid against stoptag, which are different.

This results in duplicate entries for LA Metro Rail, which uses multiple stoptags per stopid on rail.

A stoptag is supposed to denote one single platform, whereas a stopid is like the whole station.

We want one entry per station, not platform. So we should compare against el[1] (stopid), I think.
Right?

Eg. check lametro-rail.db, stopid 80301. There's two entries, differing only in the stoptag.
In the Android app, this would result in two identical stops added to the servicerequest, with the same stopids. I think.

**Comment by nighelles** [comment]
el[0] should be stopID, taken from the website. el[1] is just the name of the stop. Is it giving multiple entries per stopID?

**Comment by remulasce** [comment]
databaselist.append( (uniquetag,stopid,stopname,lat,lon) )

**Comment by remulasce** [comment]
And, yes.

**Comment by remulasce** [comment]
And correction to proposed fix: Don't add uniquetag any more, since we're not using it.

**Comment by nighelles** [comment]
Unique tag is required because the database needs a primary index term that's totally unique, and some stops don't have stopIDs. Now granted, at the moment I'm ignoring those, but it will matter when we add those.

**Comment by nighelles** [comment]
Fixed code, will update new databases.

**Comment by remulasce** [comment]
SQL lib on Android auto-generated the unque index for me. Might want to do that, since I'm not sure if NexTrip can be trusted to generate unique names like that.

**Comment by nighelles** [comment]
Ok, but I mean, like, the table actually needs to have a unique index to get saved via sqlite3. So like, I may be able to use a lib to add one in the app, but the sqlite3 engine in python won't save unless there's a primary index. And it has to be an INTEGER. So, since stopIDs are text, I used t hat.

**Comment by remulasce** [comment]
Right, see if the Python / whatever lib can generate one for you.

**Comment by nighelles** [comment]
Ok, so you just want like, an arbitrary index number. I can change that too.

**Comment by remulasce** [comment]
http://stackoverflow.com/questions/9342249/how-to-insert-a-unique-id-into-each-sqlite-row

sqlite should be able to do it for you.

**Comment by remulasce** [comment]
Looks like this should do it:
CREATE TABLE <...> ( Id INTEGER PRIMARY KEY, stuff datatype, ... )

And you can just pretend the id doesn't exist thereafter, and sqlite will deal with it for you.
(insert statements don't need a field for it. Just pretend it isn't there.)

**Comment by nighelles** [comment]
Ok, I'll look into if that actually works.

**Comment by remulasce** [comment]
Fixed by Nighelles.

**Comment by remulasce** [comment]
Future note: You don't have to specify the primary key as a column at all.

Sqlite will create one for you, and autoincrement it, if you don't specify one.
