### ISSUE TITLE
StopIDs in stopnames.db have leading zeroes

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#239]
So, Harbor Transitway / 37th St / USC station should have stopid of 2315.
But the database shows it as 02315.

This messes up some aspects of the sql lookups, since they match the stopid text and not the numeric value.
(stopids can have letters, technically)

**Comment by remulasce** [comment]
Browsing through some other agency databases, for some agencies it looks like enough leading zeroes are added to match the largest stopid. But for lametro, padding goes up to 5 digits even though there's some ridiculous 12 digit stops.

ac-transit, which Nighelles probably checked, has no problems.

**Comment by remulasce** [comment]
Ugh. Fucking NexTrip.
It's returning those leading zeroes in the routeConfig commands.
eg.
http://webservices.nextbus.com/service/publicXMLFeed?command=routeConfig&a=lametro&r=754

Seriously NexTrip, WTF?

Now we need to clean up your output, which I'm supposed to be able to feed back an input to you?

**Comment by remulasce** [comment]
Ok. I've added a line to strip leading zeroes from stopids.
Regenerating databases.

Obviously in the next bug report, some user will discover that the stopid in front of his house actually is *meant* to have a leading zero.

All this and more, with NexTrip!

**Comment by remulasce** [comment]
Ok, everything's pushed and checked.
Closing. 

Good job @nighelles .

**Comment by nighelles** [comment]
I came back to my email to find a fire I'd already put out. Good coding.
