### ISSUE TITLE
Fix issues on Android 2.3.x

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#249]
Trying out the app on old device emulator.

The dropdown autocomplete box stays open constantly, and can't be gotten rid of.

We should probably test these devices occasionally.

On the bright side, we have literally nobody running these old devices.

**Comment by remulasce** [comment]
Option 2: Just ditch the old users. Deprecate support for android 2.x

**Comment by remulasce** [comment]
Yeah, Android 2.3 is kind of fucked.

I'm removing support for it.

**Comment by nighelles** [comment]
I like your style
