### ISSUE TITLE
Final integration to java_core

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#262]
@nighelles 

I had some work on my local git repository that had not been pushed to Github from the past 2 weeks.
So I pushed that.

I think this may have included, like, all of the regionalization code.

See #237 for my old post on probably work required on your part.

**Comment by remulasce** [comment]
So after this merge, java_core should be locked.

For realsies, this time.

**Comment by nighelles** [comment]
Is this closed?

**Comment by remulasce** [comment]
Yup
