### ISSUE TITLE
Show routes to a station in the omni dropdown

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#263]
See #245 

It would be great if we could see what lines were actually going to be tracked without having to add the station.
Especially if you're unfamiliar with the exact name of all your stops, it would help make sure you're selecting the right stop.

There probably isn't enough space to actually list the number of every single line, especially to big bus depots, but we could probably fit in the line color slices before the stop names.
That would distinguish between the rail/route lines, and also help figure out if the stop you're typing is a Rapid stop or if you need to select / walk to a further station.

See #214. This would help with that for colored lines, so you could at least know you selected the right stop when you're wondering why no arrivals are showing up.

Of course, this would require scraper / sql / java_core changes.

**Comment by remulasce** [comment]
I need to learn a bit more about relational databases to see how this sort of data structure would work.

Java_core is locked, but I can write the scraper at least.

**Comment by remulasce** [comment]
Scraper has been modified.
Database files will now include a stoproutes table, with the stuff you need.

Currently regenerating all the databases...

**Comment by remulasce** [comment]
Scraping Complete.

Deleted the lametro-combined database, since we don't use it, and it would now be obselete.

**Comment by remulasce** [comment]
We don't want to change OmniAutocompleteEntry, because every time we change that class all the existing historical entries get dropped.
So unless we want to make an upgrade path for that or bundle this with a bunch of other OAE changes, we should avoid it.

**Comment by remulasce** [comment]
I think we should be able to do this almost entirely within the OmniAutoCompleteAdapter.

Right now we're not even making the views ourselves. We have a custom listitem with a textview, whose id we push to the default toString converter.

So I think we can override getView, and check if there's any known route colors to fill in there.

The getView fxn would work with the existing autocomplete entries, and just do an sql check on the stops against our new databases.

**Comment by remulasce** [comment]
So, rough tasks:
- Modify SQLPreloadedStopsReader to support stop->routes table
- New interface for stop->routes fxn
- Feed that to OmniAutoCompleteAdapter somehow
- Feed in the RouteColorer as well
- Deal with RouteColor regions. Maybe extend it to require the Agency as well.
- Add space / layout for optional color bar items
- Override getView in Adapter to add color bars.

**Comment by remulasce** [comment]
For UI, I'm going to assume we just show the color bars.
That gets you all the Rail routes, distinguishes Local from Rapid, and doesn't need much space.
We could actually probably reserve enough space for most stations without having to dynamically shuffle the sizes.

**Comment by remulasce** [comment]
Also note that the RequestList then will be the only thing missing these bars. It could look out of place.

I might even care.

**Comment by remulasce** [comment]
SQLReader is modified.

**Comment by remulasce** [comment]
Interface in.

**Comment by remulasce** [comment]
And omni input deal can see it now.

**Comment by remulasce** [comment]
AUtocompleteAdapter gets colors
Colors have <some> regions, now that Routes have Agencies.

A proper fix would be to move the colors to SQL with the rest of just about everything.
That would take quite a while longer.

**Comment by remulasce** [comment]
UIs are made.

Need to just "do it" now, I suppose.

**Comment by remulasce** [comment]
Note extra step: Determine what colors to use.

Since each request can have multiple stopids with the same route, we have to do some duplicate checking.

**Comment by remulasce** [comment]
Ok, got the colors.

Only had to fix, like, 2 things along the way.

On to actually doing the thing now.

**Comment by remulasce** [comment]
Ok, it's in. Even uses cool recycling.

Issue I think is that we're hitting the file system in the middle of getView, which is UI thread.
Need a background loader / filler, or to load it sooner somehow.

**Comment by remulasce** [comment]
They lazy load now.

I'm still a little concerned about performance. I fire a lot of asynctasks to do this stuff.

Maybe I should make #267

**Comment by remulasce** [comment]
We should probably have a 'loading' state that's differentiated from the "nothing" one.

**Comment by remulasce** [comment]
Loading state is in- White background while loading, grey when done.

**Comment by remulasce** [comment]
Actually still feels fine off debug.

Not like I'm missing a good opportunity to do this or anything.

**Comment by nighelles** [comment]
Do agencies other than LA have route colors?
