### ISSUE TITLE
On Evo Wimax (4.1.2), autocomplete view keeps popping up.

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#265]
You can't unfocus the autocompletextview properly on these devices, so the autocomplete text stays up all the time.

**Comment by remulasce** [comment]
Maybe that's why we don't have any users on lower than 4.3?

Dashboard shows overall Android users are ~20% lower than 4.3
So maybe they're all getting screwed by my UI.

**Comment by remulasce** [comment]
So the problem is, even when focus was cleared on older platforms, Android won't allow nothing to be focused.
It looks for the next focusable thing- and if there's nothing else focusable, it just refocuses the edittext.

So I've allowed the layout under the textview to be focusable, so it gets focused instead of the edittext when you tap somewhere else.

I need to test on, like, all apis now to make sure I didn't break anything else, though.

**Comment by remulasce** [comment]
Android 5: Still works
Android 4.3: Still works
Android 4.1: Fixed

**Comment by remulasce** [comment]
Hey, remember how we have analytics?

All of our uninstalls are on Android 4.1 and 2.3.
100%.

I wonder how we could have known there was a problem?

**Comment by remulasce** [comment]
Android 2.3: Focus works.
But 2.3 is still all kinds of fucked, so I'm keeping it off the supported list.

**Comment by nighelles** [comment]
Lol, android shouldn't have fragmented the shit out of their userbase.

**Comment by remulasce** [comment]
My Evo Wimax, Android 4.1, was the phone I got in 2011.

Does the iOS version still run on your high school iPhone?

**Comment by nighelles** [comment]
It's only guranteed to work on ios8 and up.

**Comment by remulasce** [comment]
I see.
