### ISSUE TITLE
Company Intranet?

### ISSUE THREAD

**Issue by nighelles** [remulasce/metroapp#275]
Where do I submit requisition requests? iOS team needs some DDR3 Ram.

**Comment by remulasce** [comment]
iOS Team already got company RAM for his laptop.

**Comment by nighelles** [comment]
I'm hearing a lot of buzz from the iOS team that andoid team must have bought that RAM from like, an evil spirit or something.

**Comment by nighelles** [comment]
iOS team says they'll buy some ram.
