### ISSUE TITLE
Figure out how we're going to do regionalization

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#278]
Options are basically either release a different app per region, or to release one master app that figures out where you are and sets itself appropriately.

Also, figure out what agencies to support for the NorCal region- just AC Transit, or we can add whatever is supported by NextBus. That might mean we need UI to show what agency is providing which trips.

The Play Store does direct keyword matching of app titles, which means people searching for a specific agency predictions will see a city-branded version as higher. But it's kind of a pain to support a whole bunch of different app releases.

**Comment by remulasce** [comment]
We should probably also release an Android version of however we do norcal regions.

**Comment by nighelles** [comment]
Ok, so the issue is that I wrote everything for regionalization except how to actually decide which region we're in.

**Comment by remulasce** [comment]
Right. So we can either write that bit, or just hardcode it in different app configurations.

**Comment by nighelles** [comment]
I don't think its that hard to write that bit, and it can be done in Java
probably?

**Comment by remulasce** [comment]
No, not hard. The Android side would need some of my recent history code redone though.
I'd say keep it out of java_core, and keep j_c as deterministic as possible. That'll let you use some better platform-specific features as well, like Google Play's built-in geofencing notifications.

The real question is if we actually want one single app for all regions. Since we only have 2 regions anyway, it might make sense to just make 2 different apps. And if we convert the Android app to multi-region, I need to change the name and let users know what's going on.

I guess we could include full region support, then also make multiple app entries using identical code and just not tell users the app actually works everywhere.

Can you check how the App Store search results work? Will including the city in the title of the app improve search hits from that city?

**Comment by nighelles** [comment]
I don't think the App Store does searches that way. Also; they frown upon
arbitrarily region restrictedapps

**Comment by remulasce** [comment]
Region-restricted like, they don't open outside a certain area? Or just any app that's only useful in one place?

**Comment by nighelles** [comment]
I think it's ok as long as there's a reason for it to only be in one region

**Comment by remulasce** [comment]
I'm feeling, do it on the platform-specific side, and then each of us should just do it how they want, as long as they have a solution for both regions.

**Comment by remulasce** [comment]
Ok, trip to Norcal. Putting together a branch for ridiculous live testing.

Looks like only SF-Muni and AC Transit are on NextBus.

Missing is:
- Bart (GTFS)
- CalTrain (??? Available, but proprietary?)
- VTA (Transloc, low-distro combined service)

Ugh.
Bart should be #1 I think, because they are using GTFS, which is a reasonable spec.
The others are just so awful. Ugh.

**Comment by nighelles** [comment]
You on skype? Let's get stuff ready for live testing.

**Comment by nighelles** [comment]
Example request:

http://api.bart.gov/api/etd.aspx?cmd=etd&orig=RICH&key=MW9S-E7SL-26DU-VV8V

**Comment by remulasce** [comment]
Ok, I propose plan:

#### Plan:
1. Settings dialog to manually set agencies
2. Default option for "automatically detect"
3. Autodetect with a service zone for each agency
  1. I think per-agency service areas work better than having a general region
  2. I can't think of any real user-facing reasons why, Maybe I want to discount agencies in the LA boonies when you're on the westside without having to define like 3 LA subregions?
  3. I think it'll make future expansion more automateable. Just throw in a new database file, with a scraped coverage area, and you're done. So we could have nationwide NextBus expansion in constant time.
4. We deploy literally the exact same app to different markets, with different names to match keywords. Or we can call it a nationwide app, and just not have to do anything more.

Manual toggling makes sense for the "travel" use case, and in the end we need a way to test-change the region anyway so we may as well make it a feature.

Then we can have the "auto-detect" agency setting automatically fill in the manual checkboxes, so when you disable autodetect it keeps the same current agencies, but lets you change them. So if you just want to add one agency, all the others you use are already checked.

#### Remaining decisions:

- Where does region-switch code live? In java_core, or per-platform?
- How do we tell the user when agency switching happens?
- How do we handle servicerequests for old agencies when we leave their region?
- How do we handle history autocomplete for out-of-region entries? (on per-platform side)
- How do we define the service area for a region? NextBus has a square geo-bounds, but what about other agencies?

**Comment by remulasce** [comment]
So step 0 of plan is to remove the old "single agency" string from regionalization helper.

Looks like it's currently only used to set the notifyservice, and as the fallback if a stop's agency isn't set.

So, reminder: NotifyService probably needs some work.

**Comment by remulasce** [comment]
Manual settings dialog now works.

**Comment by remulasce** [comment]
Improvements Remaining:

- Define a public name for the agencies, instead of showing the raw sf-muni, etc names.
  - Probably needs to happen as part of the databases
- Figure out which agencies are installed based on which .db files are present, so you don't have to hardcode them.

**Comment by remulasce** [comment]
Looking at autocompletehistory filtering. Interesting edge case: Each entry can have stops consolidated from different agencies, so what if only one of those agencies is in the current region?

I'm thinking for now, if any stop is in-region, allow the whole entry.

**Comment by remulasce** [comment]
Ooh boy. If you've got identically named stops from different agencies, you can create multiple history entries for the same-named stop, from different agencies.

Interestingly, I think this is easy to fix. We just need to move the stop consolidation to the final stage of autocomplete matching.

**Comment by remulasce** [comment]
Also, with name-consolidation, we can run into issues with multiple agencies using identical stop names. Like, imagine 2 Union Stations, or 2 Main / 2nd streets.

**Comment by remulasce** [comment]
We could probably do some proximity-based thing to not-merge those.

**Comment by remulasce** [comment]
The no-duplicate-servicerequests function doesn't check for differing agencies in the requestlist.

So that's another possible collision: Add Vermont / Athens Station with only metro-rail enabled. You get a request for only the Green Line. Then disable lametro-rail, andenable lametro. Then add Vermont / Athens Station.

Currently you won't be allowed to add the second Vermont / Athens Station, even though its agency differs from the one already added.

But if both agencies were enabled, then you wouldn't be able to convert the existing Vermont / Athens into a combo metro / rail station.

So maybe a replacement policy would work better? If the existing one is no longer in region-scope?

Man are there a lot of edge cases.

Probably need to just clear existing entries when changing regions.

**Comment by nighelles** [comment]
Region decision code probably lives in java core, but that needs to have some sort of external thing to get location, which is platform specific.

What would be nice is if all the people are pulling geo-data from some big external source that is official in some capacity. That way stations that are the same across agencies would have the EXACT same lat and long, which would make it easy to present them as the same station.

**Comment by remulasce** [comment]
OK, Android autocomplete history solution:
If an autocomplete entry contains any stop that is out of region, it doesn't get suggested.

This loses the use case where you're at some common transfer point, and want to enable another agency and expect it to have the same autocomplete priority.

But it makes the rest of the interaction a lot simpler.

**Comment by remulasce** [comment]
Actually, no. You should be able to history-select stations for individual regions, so long as we make that clear.

If a user makes a mistake when doing this, it'll get pushed out by recency calculations eventually anyway.

**Comment by remulasce** [comment]
See Milestone Auto-Regionalization for full tasks.

**Comment by remulasce** [comment]
Ok, Android version now checks what agency .db files are loaded onto the devices at startup, and loads the names / bounds from all those.

**Comment by remulasce** [comment]
Android autodetect checkbox works now.

So all remaining is to display what's going on to the user.
