### ISSUE TITLE
Multiline amounts of text in SF stop names.

### ISSUE THREAD

**Issue by nighelles** [remulasce/metroapp#279]
Some of the supplied names are too long to be displayed nicely in one line.

**Comment by remulasce** [comment]
iOS won't automatically resize to 2 lines for you?

**Comment by nighelles** [comment]
No, it won't. I need to do that on my own, or at least figure out how to get it to do it.

**Comment by nighelles** [comment]
Closing, adding to general, searchbox looks like shit issue.
