### ISSUE TITLE
Someone changed perfectly good database setup.

### ISSUE THREAD

**Issue by nighelles** [remulasce/metroapp#280]

**Comment by nighelles** [comment]
At least I think that's what's going on. Pull from qa builds fine but crashes on actually displaying stops.

**Comment by nighelles** [comment]
Could undo and go back to dev_8 build which worked, but cmon.

**Comment by nighelles** [comment]
Ok, two changes fix, again.

distance = 1 in multiarrivaltrip

and newA rather than stop in SRDP

Probably figuring out WHY these are different is important, but I'm tired.

**Comment by nighelles** [comment]
I'm getting like 3 duplicates of each route. Maybe a problem with database? Maybe a change in the storage I haven't updated for yet. Check it out, me.

**Comment by remulasce** [comment]
Sounds old. Closing.
