### ISSUE TITLE
Added Settings Dialog

### ISSUE THREAD

**Issue by nighelles** [remulasce/metroapp#291]
Doesn't really do anything yet. Other than show up.

**Comment by nighelles** [comment]
But DAMN does it show up.

**Comment by remulasce** [comment]
So, completing this dialog is priority 1.

It probably needs to be implemented differently though. Make it a full Fragment inside the dialog, and then the list of agencies should populate based on all available agencies. That way we don't have to manually change the number of checkboxes every time we add or remove agencies.

Requirements:

- One checkbox per installed agency
- One additional "Auto Detect" checkbox
- On pane open, the dialog should figure out which agencies are actually currently enabled, and check those boxes. Same for "Auto Detect".
- Checking / unchecking boxes needs to actually enable/disable those regions.
- When you check "Auto Detect", that code will probably soon change the currently enabled regions. So the dialog either needs to refresh itself occasionally, or maybe have a way to synchronously force a region update and update itself right after.

**Comment by remulasce** [comment]
Settings dialog is now moved into its own Fragment, and on load it makes a checkbox for every InstalledAgency from RegionalizationHelper instead of being hardcoded in the layout.

There's still hardcoded agencies in the layout, but they're for demo purposes. The Fragment deletes them all on load.

**Comment by remulasce** [comment]
OK, Settings Dialog now actually properly sets the agencies.

So it works, other than the "auto select" feature not existing yet.

**Comment by remulasce** [comment]
All done.

Enabling autodetect just closes the popup so we don't have to deal with rechecking when it happens.
