### ISSUE TITLE
GTFS parsing failure when trains are "leaving"

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#294]
Exception:
07-30 19:18:15.781  11747-14433/com.remulasce.lametroapp W/LaMetroUtil﹕ Unaddressed exception! Invalid int: "Leaving"

Looks like GTFS returns literally the text "leaving" in the <minutes> field occasionally. See attached return message.

<root>
<uri>
<![CDATA[ http://api.bart.gov/api/etd.aspx?cmd=etd&orig=EMBR ]]>
</uri>
<date>07/30/2015</date>
<time>07:18:03 PM PDT</time>
<station>
<name>Embarcadero</name>
<abbr>EMBR</abbr>
<etd>
<destination>Daly City</destination>
<abbreviation>DALY</abbreviation>
<estimate>
<minutes>12</minutes>
<platform>1</platform>
<direction>South</direction>
<length>8</length>
<color>BLUE</color>
<hexcolor>#0099cc</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
<estimate>
<minutes>26</minutes>
<platform>1</platform>
<direction>South</direction>
<length>8</length>
<color>BLUE</color>
<hexcolor>#0099cc</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
<estimate>
<minutes>41</minutes>
<platform>1</platform>
<direction>South</direction>
<length>8</length>
<color>BLUE</color>
<hexcolor>#0099cc</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
</etd>
<etd>
<destination>Dublin/Pleasanton</destination>
<abbreviation>DUBL</abbreviation>
<estimate>
<minutes>13</minutes>
<platform>2</platform>
<direction>North</direction>
<length>9</length>
<color>BLUE</color>
<hexcolor>#0099cc</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
<estimate>
<minutes>30</minutes>
<platform>2</platform>
<direction>North</direction>
<length>9</length>
<color>BLUE</color>
<hexcolor>#0099cc</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
<estimate>
<minutes>50</minutes>
<platform>2</platform>
<direction>North</direction>
<length>9</length>
<color>BLUE</color>
<hexcolor>#0099cc</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
</etd>
<etd>
<destination>Millbrae</destination>
<abbreviation>MLBR</abbreviation>
<estimate>
<minutes>Leaving</minutes>
<platform>1</platform>
<direction>South</direction>
<length>9</length>
<color>RED</color>
<hexcolor>#ff0000</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
</etd>
<etd>
<destination>Pittsburg/Bay Point</destination>
<abbreviation>PITT</abbreviation>
<estimate>
<minutes>10</minutes>
<platform>2</platform>
<direction>North</direction>
<length>10</length>
<color>YELLOW</color>
<hexcolor>#ffff33</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
<estimate>
<minutes>24</minutes>
<platform>2</platform>
<direction>North</direction>
<length>10</length>
<color>YELLOW</color>
<hexcolor>#ffff33</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
<estimate>
<minutes>43</minutes>
<platform>2</platform>
<direction>North</direction>
<length>9</length>
<color>YELLOW</color>
<hexcolor>#ffff33</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
</etd>
<etd>
<destination>Richmond</destination>
<abbreviation>RICH</abbreviation>
<estimate>
<minutes>2</minutes>
<platform>2</platform>
<direction>North</direction>
<length>8</length>
<color>RED</color>
<hexcolor>#ff0000</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
<estimate>
<minutes>17</minutes>
<platform>2</platform>
<direction>North</direction>
<length>9</length>
<color>RED</color>
<hexcolor>#ff0000</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
<estimate>
<minutes>36</minutes>
<platform>2</platform>
<direction>North</direction>
<length>9</length>
<color>RED</color>
<hexcolor>#ff0000</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
</etd>
<etd>
<destination>SFO/Millbrae</destination>
<abbreviation>MLBR</abbreviation>
<estimate>
<minutes>8</minutes>
<platform>1</platform>
<direction>South</direction>
<length>10</length>
<color>YELLOW</color>
<hexcolor>#ffff33</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
<estimate>
<minutes>23</minutes>
<platform>1</platform>
<direction>South</direction>
<length>10</length>
<color>YELLOW</color>
<hexcolor>#ffff33</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
<estimate>
<minutes>38</minutes>
<platform>1</platform>
<direction>South</direction>
<length>2</length>
<color>YELLOW</color>
<hexcolor>#ffff33</hexcolor>
<bikeflag>1</bikeflag>
</estimate>
</etd>
</station>
<message/>
</root>

**Comment by nighelles** [comment]
Lol

**Comment by nighelles** [comment]
In the minutes place? I can't read the xml, just the text.

**Comment by remulasce** [comment]
Yes. Minutes place reads "leaving" or some text instead of a number
