### ISSUE TITLE
bart stations display as "0yd" away

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#295]
I think 0yd is the default value for "doesn't have a location attached"

Don't know why it only happens on bart. I'd imagine the database file doesn't have the locations put in, but I thought I saw you had added them.

**Comment by nighelles** [comment]
I thought I did, I'll check it out. Maybe does it do something across
different classes by looking up by vehicle number?

**Comment by remulasce** [comment]
Fixed at 8ef7d0

Issue was in LaMetroUtil during stop.isValid, threw an exception because BART uses letters in their stopids.
