### ISSUE TITLE
Dropdown activates when you exit any dialog, even though the about pane is open

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#296]
So, 2 issues:

Closing a dialog shouldn't activate the dropdown, only app open
The dropdown should never be shown while the about pane is open. At minimum, close the pane when that happens.

This is probably API dependent. Observed on 5.1 Sense / HTC One m9

**Comment by nighelles** [comment]
Confirmed on whatever this device is as well.

**Comment by remulasce** [comment]
See #266, probably duplicate / similar

**Comment by remulasce** [comment]
Fixed.
