### ISSUE TITLE
Agency service area definition

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#297]
We need a way to determine what agencies should be active for a given location.

I'm thinking, we should automate this in the scraper and shove it in an Agency Info table.
That way we don't have to manually define things.

While we're at it, see what else we can define per-agency, like the proper name to display, etc.

**Comment by remulasce** [comment]
NextBus API provides latMin and latMax for each route.

So we could use the max bounds of any route as the entire agency's boundary, plus like 5 miles or something.

**Comment by remulasce** [comment]
NexTrip is now regenerated.

agencyinfo table in each .db has name, proper name, and lat/lon boundary info included.

@Nighelles should do the same to his gtfs scraper.

**Comment by nighelles** [comment]
Did it, didn't have agency max and min, just calculated it as we go through the stops.
