### ISSUE TITLE
Display Agencies to user

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#299]
User needs to know what agencies are enabled, and what agencies are being shown for each stop.

A bad failure case would be if user adds a stop he thinks contains a certain agency, but doesn't, therefore he thinks his route isn't coming instead of just isn't added.

Minimum: Input bar, and request list.
Maybe see what we can do about in-trip as well, but that's a lot of duplicated space.

**Comment by remulasce** [comment]
We might need a shortened version of each agency's name. Hopefully that's defined somewhere.

Unhelpfully, none of these agencies will let you use their logos anywhere. That would have been too easy, probably.

**Comment by nighelles** [comment]
How about just a little graphic with plain text for each agency. Like, all caps text.

**Comment by remulasce** [comment]
Because it takes a lot of space. And some of these agencies have really long names, and don't provide shorter ones.

I guess I'm thinking, we already don't tell the user which routes are coming to each stop. So not telling them the agency either isn't making much of a difference. And for the stops you use every day, you'd learn pretty quick which stop has the right agency and route.

So if we want to really teach the user what's going to happen and which stops to add, it's like we should make a whole separate view for doing that, with the full big mapview and pretty lines, etc. 

But if we just want to describe what's going on, we don't actually have enough space for everything.

Maybe middle ground is we rejigger the tap-trip-to-select to show more details, with notify service as an option within? That's probably workable.

**Comment by remulasce** [comment]
Thinking some more about this today. Tap-to-view-details seems the most reasonable today, too.

**Comment by nighelles** [comment]
But then wouldn't you have to already have selected the stop in order to
see what the agency is? That seems like a lot of work if there's two
different stops you think might be right.

-Nighelles

**Comment by remulasce** [comment]
Yes.

So I mentioned in an earlier thread, the app is already bad for beginners,
because there's no map and you have to know the name of your stop, unless
you're running a bootleg iOS version and see literally standing on glue
stop.

So I think its acceptable to force the user to make one mistake, in later
to learn their stop name every other time they use the app.

Basically assume user is experienced, and only provide user enough info to
go from intermediate to experienced.

A future "accessibility" update might add a map feature  but would require
a ton of work to make it accessible. So better to forget about beginners
for now than to half-add one part of accessibility in this case.

**Comment by nighelles** [comment]
Woah, woah. The iOS version is totally authorized.

**Comment by remulasce** [comment]
Authorized.. By Apple, for distribution in their App Store? Or by some
other entity?
