### ISSUE TITLE
Java serialization not implemented in j2objc

### ISSUE THREAD

**Issue by nighelles** [remulasce/metroapp#304]
So, I was planning to use serialization in combination with NSUserDefaults to save preferences in a way that would allow me to make the Java_core preference saving work.

However, it looks like serialization isn't actually implemented by j2objc, so I need to figure out another way to make this work.

-Nighelles

**Comment by remulasce** [comment]
Technically a persistence deal shouldn't be required to use RegionalizationHelper, it just totally sucks for the user if his settings get reset every time.

Pushed some commits that should ease some dependency problems, and handle missing Persistence / Location modules more gracefully.

**Comment by nighelles** [comment]
Wrote a thing, so at least the piece is there now. I'll pull your commit.
